# @format

os: linux
dist: focal
language: node_js
node_js:
  - 14

before_install:
  - sudo apt-get -y install curl

jobs:
  include:
    - stage: DemoFull
      script:
        - cd DemoFull && npm install && npm build
    - stage: Imuv
      script:
        - cd Imuv && npm install && npm build
    - stage: ImuvEditor
      script:
        - cd ImuvEditor && npm install && npm build
    - stage: ImuvServer
      script:
        - cd ImuvServer && npm install && npm build
    - stage: SimpleServer
      script:
        - cd SimpleServer && npm install && npm build
    - stage: trigger downstream
      script:
      - |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
        ls -al trigger-travis.sh
        if [[ ($TRAVIS_BRANCH == master) && ($TRAVIS_PULL_REQUEST == false) ]] ; then
          echo "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          curl -LO --retry 3 https://raw.githubusercontent.com/plume-lib/trigger-travis/master/trigger-travis.sh
          echo "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
          sh trigger-travis.sh VCityTeam UD-Viz-demo-docker $TRAVIS_ACCESS_TOKEN
          echo "ccccccccccccccccccccccccccccccccccccccccccc"
        else
          echo "trigger-travis.sh did not run"
        fi
