# @format

os: linux
dist: focal
language: node_js
node_js:
  - 15

before_install:
  - npm --version

install:
  - npm install

jobs:
  include:
    - stage: testImuv
      script:
        - cd Imuv && npm i && npm run build
