# @format

os: linux
dist: focal
language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: DemoFull
      script:
        - cd DemoFull && npm install && npm build
    - stage: Imuv
      script:
        - cd Imuv && npm install && npm build
    - stage: ImuvEditor
      script:
        - cd ImuvEditor && npm install && npm build
    - stage: ImuvServer
      script:
        - cd ImuvServer && npm install && npm build
    - stage: SimpleServer
      script:
        - cd SimpleServer && npm install && npm build
