os: linux
dist: focal
language: node_js
node_js:
  - 15

before_install:
  - npm --version

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
        - npm run build
  # - stage: lint
  #   script:
  #     - ./node_modules/eslint/bin/eslint.js --version
  #     - npm run lint
